In [2]:
import pandas as pd

In [5]:
ais = pd.read_csv('C:/Users/user/Desktop/항만운영정보시스템data/ModelingDataset/ais.csv',sep=',', encoding = 'cp949', index_col = 0) # ais정보로 바꾸기
portmis = pd.read_csv('C:/Users/user/Desktop/항만운영정보시스템data/ModelingDataset/portmis.csv',sep=',', encoding = 'cp949' ,index_col = 0)

In [6]:
portmis

,항명,호출부호,mmsi,선명,구분,외내,입출,총톤수,입항일시,출항일시,전출항지,선박용도
0,인천,3FDX9,371369000.0,POS BANGKOK,최종,외항,입항,"18,085",2022-11-30 00:36,2022-11-30 13:54,SHANTOU,풀컨테이너선
1,인천,D7SK,441791000.0,코리아비너스,최종,내항,입항,"29,543",2022-11-30 08:55,2022-12-01 08:55,여수,석유제품 운반선
2,인천,DSPF9,440918000.0,BONANZA,최종,외항,입항,"3,690",2022-11-30 12:50,2022-12-01 06:10,대산,케미칼 운반선
3,인천,C6TM5,311697000.0,MORNING CALM,최종,외항,입항,"57,692",2022-11-30 14:05,2022-12-04 10:40,QINGDAO,자동차운반선
4,인천,DSME,440432000.0,우림 7,최종,내항,입항,"8,072",2022-11-30 16:05,2022-12-01 14:25,울산,석유제품 운반선
...,...,...,...,...,...,...,...,...,...,...,...,...
892,인천,V7A4986,538009640.0,KOBE TRADER,최종,외항,입항,"9,944",2022-12-30 19:00,2022-12-31 07:00,SHANTOU,풀컨테이너선
893,인천,5LDT2,636021396.0,ZIM AUSTRALIA,최종,외항,입항,"10,308",2022-12-30 19:12,2022-12-31 06:06,부산,풀컨테이너선
894,인천,130081,440061040.0,은성호,최종,내항,입항,321,2022-12-30 20:50,2022-12-31 14:05,대산,석유제품 운반선
895,인천,D7QA,440525000.0,거제 코델리아,최종,내항,입항,"8,689",2022-12-30 21:00,2022-12-31 10:40,대산,석유제품 운반선
896,인천,9HA5618,229869000.0,PS AMALFI,최종,외항,입항,"60,185",2022-12-30 21:15,2023-01-01 13:12,HONG KONG,석유제품 운반선

In [7]:
shipList = list(portmis['mmsi'])
shipList

[371369000.0,
 441791000.0,
 440918000.0,
 311697000.0,
 440432000.0,
 538005313.0,
 538009208.0,
 538005898.0,
 477311800.0,
 667001943.0,
 563139700.0,
 477585400.0,
 235086166.0,
 440121610.0,
 440655000.0,
 441953000.0,
 538008860.0,
 440011240.0,
 440753304.0,
 413073000.0,
 538003355.0,
 352001353.0,
 667002134.0,
 538008859.0,
 440058060.0,
 538003439.0,
 564215900.0,
 636018529.0,
 533180215.0,
 538007503.0,
 630001010.0,
 412500614.0,
 414727000.0,
 440017150.0,
 440010160.0,
 440328160.0,
 440509320.0,
 441287000.0,
 181823.0,
 354138000.0,
 440021230.0,
 440000910.0,
 370403000.0,
 441289000.0,
 440218340.0,
 477548100.0,
 440058710.0,
 636021614.0,
 440419000.0,
 312807000.0,
 440120300.0,
 312291000.0,
 636021595.0,
 440022920.0,
 440555000.0,
 312045000.0,
 440148840.0,
 440026590.0,
 432809000.0,
 352001622.0,
 374990000.0,
 441103000.0,
 440194890.0,
 441376000.0,
 219029742.0,
 440375000.0,
 312543000.0,
 311037400.0,
 440109610.0,
 312597000.0,
 440108910.0,
 440102820.0,
 352906000.0,
 440010160.0,
 352001513.0,
 440108460.0,
 477154400.0,
 255806127.0,
 944402.0,
 538005896.0,
 440010160.0,
 441953000.0,
 440413160.0,
 373363000.0,
 412204480.0,
 440500014.0,
 440153960.0,
 440011240.0,
 255806072.0,
 715132501.0,
 209138000.0,
 440002200.0,
 413453650.0,
 538010246.0,
 440117608.0,
 563121100.0,
 538002624.0,
 440525000.0,
 440019380.0,
 440057510.0,
 352002211.0,
 412500614.0,
 311272000.0,
 440413000.0,
 440328160.0,
 235111726.0,
 412202870.0,
 310644000.0,
 440061040.0,
 440017180.0,
 373213000.0,
 352978155.0,
 440026590.0,
 440010160.0,
 477629500.0,
 355985000.0,
 249717000.0,
 538006980.0,
 440006980.0,
 441610000.0,
 440005120.0,
 440022920.0,
 373836000.0,
 440977000.0,
 440017150.0,
 538007718.0,
 563077000.0,
 441103000.0,
 312236000.0,
 440403000.0,
 312933000.0,
 440030880.0,
 477193400.0,
 441918000.0,
 538009319.0,
 440403700.0,
 441737000.0,
 636019190.0,
 441791000.0,
 508111131.0,
 370758000.0,
 372582000.0,
 312408000.0,
 667001307.0,
 440010160.0,
 440026590.0,
 440019380.0,
 312920000.0,
 373316000.0,
 413377920.0,
 441953000.0,
 450782176.0,
 538009733.0,
 441376000.0,
 355297000.0,
 312724000.0,
 477201800.0,
 563143100.0,
 440280000.0,
 477637200.0,
 440153960.0,
 228408700.0,
 312235000.0,
 477154400.0,
 574102378.0,
 636011902.0,
 440401000.0,
 440403850.0,
 440030880.0,
 440010160.0,
 636019606.0,
 370322000.0,
 440128840.0,
 440017150.0,
 538010048.0,
 440021230.0,
 441885000.0,
 441862000.0,
 538007312.0,
 255708000.0,
 440026590.0,
 440184000.0,
 440413000.0,
 441198000.0,
 441567000.0,
 441067000.0,
 440189720.0,
 440014870.0,
 440525000.0,
 636014894.0,
 440148840.0,
 538010219.0,
 440198420.0,
 308234000.0,
 563157300.0,
 538008590.0,
 440000560.0,
 538008691.0,
 374302000.0,
 440108460.0,
 440002030.0,
 563046100.0,
 373808000.0,
 412500614.0,
 414690000.0,
 538009820.0,
 440192230.0,
 370531000.0,
 312405000.0,
 440120300.0,
 355188000.0,
 636091575.0,
 440061040.0,
 441953000.0,
 538009208.0,
 441890000.0,
 440518000.0,
 412202870.0,
 440022920.0,
 440870000.0,
 440013130.0,
 636019317.0,
 440419000.0,
 574102378.0,
 353201000.0,
 566231076.0,
 311003600.0,
 440194890.0,
 477548900.0,
 636019057.0,
 440328160.0,
 440074350.0,
 311272000.0,
 312716000.0,
 441510000.0,
 477154400.0,
 636092854.0,
 440021230.0,
 667001517.0,
 441103000.0,
 636018638.0,
 440918000.0,
 414489000.0,
 440010160.0,
 440660000.0,
 477276100.0,
 440019380.0,
 636021814.0,
 440121610.0,
 440153960.0,
 563412000.0,
 352001826.0,
 440190000.0,
 440026590.0,
 311594000.0,
 312268000.0,
 477978400.0,
 373788000.0,
 440152450.0,
 563127300.0,
 441127000.0,
 440162170.0,
 209539000.0,
 355188000.0,
 412204480.0,
 440010160.0,
 441563000.0,
 538009630.0,
 412500614.0,
 440413000.0,
 440005120.0,
 441288000.0,
 440414520.0,
 374990000.0,
 257532000.0,
 441791000.0,
 440328160.0,
 373750000.0,
 440119760.0,
 538010152.0,
 440192230.0,
 440198690.0,
 354467000.0,
 440711900.0,
 441953000.0,
 440057510.0,
 441933000.0,
 440021230.0,
 440119210.0,
 440022920.0,
 440013130.0,
 413222810.0,
 440153960.0,
 440498000.0,
 352001183.0,
 440153810.0,
 440016180.0,
 538005313.0,
 441287000.0,
 441174000.0,
 538010006.0,
 440509320.0,
 356222000.0,
 414568000.0,
 232024772.0,
 440030880.0,
 440011240.0,
 538008815.0,
 440403850.0,
 440501060.0,
 352978214.0,
 440109590.0,
 440010160.0,
 477154400.0,
 440074350.0,
 538008168.0,
 538005864.0,
 312289000.0,
 440525000.0,
 440017150.0,
 440059000.0,
 374666000.0,
 477716100.0,
 440061040.0,
 441199000.0,
 440178000.0,
 309759000.0,
 441283000.0,
 441400000.0,
 440375000.0,
 538007311.0,
 636019897.0,
 412202870.0,
 312600000.0,
 538009640.0,
 355188000.0,
 412500614.0,
 413442920.0,
 440010160.0,
 440030880.0,
 440019380.0,
 533180090.0,
 440148840.0,
 441607000.0,
 440005120.0,
 440153810.0,
 538010005.0,
 441953000.0,
 373316000.0,
 440066770.0,
 354138000.0,
 440061040.0,
 440119760.0,
 440022920.0,
 440058060.0,
 352002104.0,
 311272000.0,
 440072080.0,
 441198000.0,
 440504300.0,
 440115000.0,
 574493000.0,
 563181000.0,
 440016180.0,
 312888000.0,
 352001679.0,
 441405000.0,
 440432000.0,
 219602000.0,
 312016000.0,
 241352000.0,
 440010160.0,
 441469000.0,
 563093800.0,
 352002188.0,
 441030000.0,
 353861000.0,
 440030880.0,
 667001307.0,
 372275000.0,
 354401000.0,
 248264000.0,
 441730000.0,
 413453650.0,
 440977000.0,
 373143000.0,
 440057510.0,
 312729000.0,
 440074350.0,
 412204480.0,
 440005120.0,
 440108910.0,
 477154400.0,
 312058000.0,
 440525000.0,
 538009208.0,
 354958000.0,
 440026590.0,
 440102820.0,
 667001733.0,
 373215000.0,
 440010160.0,
 440021230.0,
 440058710.0,
 351131000.0,
 440014870.0,
 440153960.0,
 440019380.0,
 440413160.0,
 370469000.0,
 440328160.0,
 305235000.0,
 441953000.0,
 477413300.0,
 440017150.0,
 308234000.0,
 440017180.0,
 440432000.0,
 636021360.0,
 441502000.0,
 441271000.0,
 311594000.0,
 374302000.0,
 312400000.0,
 440775000.0,
 477594900.0,
 412500614.0,
 667001619.0,
 440010160.0,
 235067987.0,
 440189720.0,
 441508000.0,
 440022920.0,
 440194890.0,
 441791000.0,
 441425000.0,
 441312000.0,
 636019161.0,
 563159700.0,
 412331380.0,
 440585000.0,
 414690000.0,
 636017768.0,
 356421000.0,
 636021396.0,
 563382000.0,
 538005898.0,
 312642000.0,
 440413160.0,
 477301900.0,
 441387000.0,
 440026590.0,
 440403850.0,
 440148840.0,
 440005120.0,
 232024773.0,
 371369000.0,
 353727000.0,
 440162170.0,
 215009000.0,
 440061040.0,
 538008215.0,
 563955000.0,
 441768000.0,
 412202870.0,
 212546000.0,
 477466300.0,
 312664000.0,
 440121610.0,
 440120300.0,
 440003200.0,
 441610000.0,
 412500614.0,
 412429154.0,
 440153960.0,
 440000910.0,
 374990000.0,
 312738000.0,
 356928000.0,
 440328160.0,
 441288000.0,
 538006909.0,
 312656000.0,
 440010160.0,
 441199000.0,
 440074350.0,
 441077000.0,
 441470000.0,
 372604000.0,
 477154400.0,
 440019380.0,
 440022920.0,
 441953000.0,
 533180215.0,
 440013130.0,
 538005896.0,
 441376000.0,
 477066600.0,
 440660000.0,
 311272000.0,
 440153810.0,
 441722000.0,
 636022205.0,
 241636000.0,
 538005387.0,
 538005313.0,
 441510000.0,
 636021480.0,
 440121610.0,
 440011240.0,
 352898704.0,
 440005120.0,
 440010160.0,
 312278000.0,
 538005482.0,
 441607000.0,
 440017150.0,
 441067000.0,
 441198000.0,
 538007485.0,
 255806168.0,
 440021230.0,
 351230000.0,
 440178000.0,
 312419000.0,
 563145300.0,
 440525000.0,
 636021011.0,
 412500614.0,
 440005120.0,
 538008860.0,
 440010160.0,
 538009022.0,
 440066770.0,
 312896000.0,
 440375000.0,
 353290000.0,
 441520000.0,
 636015481.0,
 209138000.0,
 715132501.0,
 440011240.0,
 440026590.0,
 412476975.0,
 563163500.0,
 636021955.0,
 309601000.0,
 538008859.0,
 441553000.0,
 441509000.0,
 441292000.0,
 352001411.0,
 414568000.0,
 441588000.0,
 352119000.0,
 441289000.0,
 312600000.0,
 412204480.0,
 563157300.0,
 563121100.0,
 440775000.0,
 412202870.0,
 373917000.0,
 441953000.0,
 440192230.0,
 477947600.0,
 440148840.0,
 441791000.0,
 440017150.0,
 440153960.0,
 440024420.0,
 441223000.0,
 355188000.0,
 636091255.0,
 477154400.0,
 440030880.0,
 440153810.0,
 440101220.0,
 440328160.0,
 440498000.0,
 441610000.0,
 477745800.0,
 440019380.0,
 440010160.0,
 440057510.0,
 538008836.0,
 441588000.0,
 440403700.0,
 440401000.0,
 440419000.0,
 441183000.0,
 241163000.0,
 373316000.0,
 440525000.0,
 667001727.0,
 538009208.0,
 440134720.0,
 308234000.0,
 538006710.0,
 440194890.0,
 440002030.0,
 441510000.0,
 440116190.0,
 441567000.0,
 441229000.0,
 440556000.0,
 441508000.0,
 440021230.0,
 440119760.0,
 412500614.0,
 312237000.0,
 312152000.0,
 440218340.0,
 440010160.0,
 413453650.0,
 440509320.0,
 440520000.0,
 440190000.0,
 636015686.0,
 440328160.0,
 311003200.0,
 440192230.0,
 440058060.0,
 440019380.0,
 311000103.0,
 441199000.0,
 440005120.0,
 440101220.0,
 440061040.0,
 440687000.0,
 440011240.0,
 440026590.0,
 374922000.0,
 477585400.0,
 441424000.0,
 538003677.0,
 440016180.0,
 441953000.0,
 440413160.0,
 414690000.0,
 412408080.0,
 440120300.0,
 440500014.0,
 440006000.0,
 374816000.0,
 566286000.0,
 374205000.0,
 440128230.0,
 440403850.0,
 356725000.0,
 440660000.0,
 441470000.0,
 566073000.0,
 312673000.0,
 440002200.0,
 440010160.0,
 354138000.0,
 477537400.0,
 538090492.0,
 440074350.0,
 440061040.0,
 311272000.0,
 538009820.0,
 440005120.0,
 441077000.0,
 440119760.0,
 440021230.0,
 440017150.0,
 440058710.0,
 440019380.0,
 312134000.0,
 440153960.0,
 636091575.0,
 477856600.0,
 636020254.0,
 477154400.0,
 412500614.0,
 440014870.0,
 440072080.0,
 440147000.0,
 440525000.0,
 374990000.0,
 477105700.0,
 563158400.0,
 210461000.0,
 352851000.0,
 373876000.0,
 440088000.0,
 312418000.0,
 373407000.0,
 667001766.0,
 440514000.0,
 538007661.0,
 636017724.0,
 255601240.0,
 441791000.0,
 352019000.0,
 373595000.0,
 477348200.0,
 636021678.0,
 440328160.0,
 667001979.0,
 440010160.0,
 440019380.0,
 440153960.0,
 441510000.0,
 374302000.0,
 440059000.0,
 440011240.0,
 440403850.0,
 440192230.0,
 441289000.0,
 440414520.0,
 440427000.0,
 636022203.0,
 440328160.0,
 441103000.0,
 563049100.0,
 412202870.0,
 440413160.0,
 538005864.0,
 441953000.0,
 440016180.0,
 354159000.0,
 441730000.0,
 538009630.0,
 715132501.0,
 441283000.0,
 636021813.0,
 441127000.0,
 255805676.0,
 440061040.0,
 440148840.0,
 215011000.0,
 440150720.0,
 440178000.0,
 339301320.0,
 440655000.0,
 440192230.0,
 565158000.0,
 311272000.0,
 538005313.0,
 538010176.0,
 351031000.0,
 440019380.0,
 416492000.0,
 440525000.0,
 352002104.0,
 312857000.0,
 477157300.0,
 477154400.0,
 312897000.0,
 440005120.0,
 229334000.0,
 441198000.0,
 440010160.0,
 312405000.0,
 209539000.0,
 440775000.0,
 440017180.0,
 636019478.0,
 412204480.0,
 441862000.0,
 440152450.0,
 373316000.0,
 440403850.0,
 440192230.0,
 538009716.0,
 312933000.0,
 440095000.0,
 440074350.0,
 441755000.0,
 441607000.0,
 440403700.0,
 353861000.0,
 440026590.0,
 538009319.0,
 441510000.0,
 574252000.0,
 440153960.0,
 312925000.0,
 374842000.0,
 440432000.0,
 441279000.0,
 308234000.0,
 440003200.0,
 412331380.0,
 511294000.0,
 441953000.0,
 538008691.0,
 440066770.0,
 440019380.0,
 412500614.0,
 440010160.0,
 351230000.0,
 441659000.0,
 355231000.0,
 667001517.0,
 441610000.0,
 256143000.0,
 266283000.0,
 440061040.0,
 441023000.0,
 440711900.0,
 440375000.0,
 538005981.0,
 352001968.0,
 636017562.0,
 440058060.0,
 440011240.0,
 440119760.0,
 538009995.0,
 441421000.0,
 441030000.0,
 441103000.0,
 413453650.0,
 440501060.0,
 440024420.0,
 352170000.0,
 441400000.0,
 353201000.0,
 440400400.0,
 351394000.0,
 312336000.0,
 441278000.0,
 636014590.0,
 538007312.0,
 440002030.0,
 356970000.0,
 440010160.0,
 440525000.0,
 355170000.0,
 441376000.0,
 441271000.0,
 440189720.0,
 440977000.0,
 477154400.0,
 440021230.0,
 351050000.0,
 440152450.0,
 441902000.0,
 538007487.0,
 440328160.0,
 440419000.0,
 440010160.0,
 412202870.0,
 440403850.0,
 563256000.0,
 440134720.0,
 441791000.0,
 441067000.0,
 538010298.0,
 538003294.0,
 441953000.0,
 440005120.0,
 440016180.0,
 312362000.0,
 412500614.0,
 440153960.0,
 671048100.0,
 538009680.0,
 353800000.0,
 440010160.0,
 255806072.0,
 312773000.0,
 440058710.0,
 440120300.0,
 440413160.0,
 440660000.0,
 311000103.0,
 440192230.0,
 538010048.0,
 441174000.0,
 371369000.0,
 440301800.0,
 440148840.0,
 440011240.0,
 636017768.0,
 232012490.0,
 440150720.0,
 352001275.0,
 441510000.0,
 538005981.0,
 477842900.0,
 440192230.0,
 440074350.0,
 440010160.0,
 311272000.0,
 613003641.0,
 440017150.0,
 538005898.0,
 305977000.0,
 538009640.0,
 636021396.0,
 440061040.0,
 440525000.0,
 229869000.0]

In [8]:
shiplog = ais[ais['mmsi'].isin(shipList)]
shiplog

                  insertTime       mmsi  speed    shipLat     shipLon
11       2022-11-30 16:33:05  371369000   17.1  37.264305  126.245270
12       2022-11-30 16:33:05  440022920    0.0  37.452236  126.610077
23       2022-11-30 16:33:05  235086166    9.7  37.004253  126.162865
34       2022-11-30 16:33:05  440022920    0.0  37.452225  126.610085
39       2022-11-30 16:33:05  441103000    5.3  37.327690  126.510292
...                      ...        ...    ...        ...         ...
2298236  2022-12-30 00:50:04  538010048    2.8  37.339527  126.634224
2298238  2022-12-30 00:50:05  441174000   11.7  37.188816  126.381104
2298246  2022-12-30 00:50:06  538007487   14.6  37.330166  126.456902
2298249  2022-12-30 00:50:07  538010048    2.8  37.339565  126.415787
2298253  2022-12-30 00:50:08  440017180    0.0  37.482044  126.398361

[311146 rows x 5 columns]

In [9]:
shiplog.reset_index(drop=True, inplace = True)

In [10]:
shiplog

                 insertTime       mmsi  speed    shipLat     shipLon
0       2022-11-30 16:33:05  371369000   17.1  37.264305  126.245270
1       2022-11-30 16:33:05  440022920    0.0  37.452236  126.610077
2       2022-11-30 16:33:05  235086166    9.7  37.004253  126.162865
3       2022-11-30 16:33:05  440022920    0.0  37.452225  126.610085
4       2022-11-30 16:33:05  441103000    5.3  37.327690  126.510292
...                     ...        ...    ...        ...         ...
311141  2022-12-30 00:50:04  538010048    2.8  37.339527  126.634224
311142  2022-12-30 00:50:05  441174000   11.7  37.188816  126.381104
311143  2022-12-30 00:50:06  538007487   14.6  37.330166  126.456902
311144  2022-12-30 00:50:07  538010048    2.8  37.339565  126.415787
311145  2022-12-30 00:50:08  440017180    0.0  37.482044  126.398361

[311146 rows x 5 columns]

In [11]:
shiplog.to_csv('C:/Users/user/Desktop/항만운영정보시스템data/ModelingDataset/shiplog.csv')

In [12]:
df = pd.read_csv('C:/Users/user/Desktop/항만운영정보시스템data/ModelingDataset/shiplog.csv', index_col = 0)

In [13]:
df

                 insertTime       mmsi  speed    shipLat     shipLon
0       2022-11-30 16:33:05  371369000   17.1  37.264305  126.245270
1       2022-11-30 16:33:05  440022920    0.0  37.452236  126.610077
2       2022-11-30 16:33:05  235086166    9.7  37.004253  126.162865
3       2022-11-30 16:33:05  440022920    0.0  37.452225  126.610085
4       2022-11-30 16:33:05  441103000    5.3  37.327690  126.510292
...                     ...        ...    ...        ...         ...
311141  2022-12-30 00:50:04  538010048    2.8  37.339527  126.634224
311142  2022-12-30 00:50:05  441174000   11.7  37.188816  126.381104
311143  2022-12-30 00:50:06  538007487   14.6  37.330166  126.456902
311144  2022-12-30 00:50:07  538010048    2.8  37.339565  126.415787
311145  2022-12-30 00:50:08  440017180    0.0  37.482044  126.398361

[311146 rows x 5 columns]